from enum import Enum, auto


# https://github.com/ggml-org/llama.cpp/blob/master/ggml/include/ggml.h
class GGML_TYPE(Enum):
    F32 = 0  # auto() starts with 1
    F16 = auto()
    Q4_0 = auto()
    Q4_1 = auto()
    Q4_2 = auto()  # (removed)
    Q4_3 = auto()  # (removed)
    Q5_0 = auto()
    Q5_1 = auto()
    Q8_0 = auto()
    Q8_1 = auto()
    Q2_K = auto()
    Q3_K = auto()
    Q4_K = auto()
    Q5_K = auto()
    Q6_K = auto()
    Q8_K = auto()
    IQ2_XXS = auto()
    IQ2_XS = auto()
    IQ3_XXS = auto()
    IQ1_S = auto()
    IQ4_NL = auto()
    IQ3_S = auto()
    IQ2_S = auto()
    IQ4_XS = auto()
    I8 = auto()
    I16 = auto()
    I32 = auto()
    I64 = auto()
    F64 = auto()
    IQ1_M = auto()
    BF16 = auto()
    Q4_0_4_4 = auto()  # (removed)
    Q4_0_4_8 = auto()  # (removed)
    Q4_0_8_8 = auto()  # (removed)
    TQ1_0 = auto()
    TQ2_0 = auto()
    IQ4_NL_4_4 = auto()  # (removed)
    IQ4_NL_4_8 = auto()  # (removed)
    IQ4_NL_8_8 = auto()  # (removed)
